//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AggScore
    {
        public string COURSE_NO { get; set; }
        public string DISCIPLINE { get; set; }
        public string AGG_MIDTERM { get; set; }
        public string AGG_ASSI { get; set; }
        public string AGG_FINAL { get; set; }
        public string AGG_PRACA { get; set; }
        public Nullable<decimal> AGG_PRACB { get; set; }
        public Nullable<decimal> AGG_PRACC { get; set; }
        public Nullable<decimal> AGG_PRACD { get; set; }
        public Nullable<decimal> AGG_PRACE { get; set; }
        public string SOS { get; set; }
    }
}
