//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHALLAN
    {
        public string Reg_no { get; set; }
        public string Final_Course { get; set; }
        public string Semester_no { get; set; }
        public Nullable<decimal> Sem_Fee { get; set; }
        public Nullable<decimal> Reg_Fee { get; set; }
        public Nullable<decimal> Adm_Fee { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Inst_No { get; set; }
        public Nullable<decimal> Disc_Amt { get; set; }
        public Nullable<decimal> Net_amt { get; set; }
        public string Installments { get; set; }
        public Nullable<decimal> Inst_amt { get; set; }
        public string Reciept_no { get; set; }
        public Nullable<decimal> Fine { get; set; }
        public string SOS { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<decimal> ExtraCourse_Fee { get; set; }
        public Nullable<decimal> Other_Fee { get; set; }
        public Nullable<int> SemC { get; set; }
        public Nullable<int> Issue_time { get; set; }
        public string Fee_type { get; set; }
        public Nullable<int> issue_fine { get; set; }
        public Nullable<bool> Paid_ { get; set; }
        public Nullable<int> Sch_amt { get; set; }
        public Nullable<decimal> Total_Payable { get; set; }
        public string App_no { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> ReIssue { get; set; }
    }
}
