//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrsEnrF
    {
        public string REG_NO { get; set; }
        public string DISCIPLINE { get; set; }
        public string Course_no { get; set; }
        public string Course_desc { get; set; }
        public string emp_no { get; set; }
        public string semester_no { get; set; }
        public Nullable<int> Attempt_no { get; set; }
        public string grade { get; set; }
    }
}
