//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRSMTR
    {
        public string Course_no { get; set; }
        public string Discipline { get; set; }
        public string Course_desc { get; set; }
        public string Credit_hrs { get; set; }
        public string Course_type { get; set; }
        public string SOS { get; set; }
        public string SOS_DESC { get; set; }
        public Nullable<int> ELective_course { get; set; }
        public string Old_SOS { get; set; }
    }
}
