//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRSPRE
    {
        public string COURSE_NO { get; set; }
        public string DISCIPLINE { get; set; }
        public string SOS { get; set; }
        public string PreCOURSE_NO { get; set; }
    }
}
