//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DscplnEntry
    {
        public string Final_Course { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public Nullable<decimal> regFee { get; set; }
        public Nullable<decimal> admFee { get; set; }
        public string Desc { get; set; }
        public int SemC { get; set; }
        public Nullable<System.DateTime> DefDueDate { get; set; }
        public Nullable<int> fine1 { get; set; }
        public Nullable<int> fine2 { get; set; }
        public Nullable<int> fine3 { get; set; }
    }
}
