//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstDate2
    {
        public int inst_no { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public Nullable<System.DateTime> duedate1 { get; set; }
        public Nullable<System.DateTime> duedate2 { get; set; }
        public Nullable<System.DateTime> duedate3 { get; set; }
    }
}
