//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class meritTemp
    {
        public string App_no { get; set; }
        public string St_firstname { get; set; }
        public string St_lastname { get; set; }
        public string St_middlename { get; set; }
        public string Father_name { get; set; }
        public string Semester_no { get; set; }
        public string Final_course { get; set; }
        public string Discipline { get; set; }
        public Nullable<double> Obj_score { get; set; }
        public Nullable<double> Total_score { get; set; }
        public Nullable<double> Percentage { get; set; }
    }
}
