//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class survey_monkey_databaseEntities1 : DbContext
    {
        public survey_monkey_databaseEntities1()
            : base("name=survey_monkey_databaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accgpa> Accgpas { get; set; }
        public virtual DbSet<ActiveSurvey> ActiveSurveys { get; set; }
        public virtual DbSet<AggScore> AggScores { get; set; }
        public virtual DbSet<Alert> Alerts { get; set; }
        public virtual DbSet<AlertUser> AlertUsers { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<CHALLAN> CHALLANs { get; set; }
        public virtual DbSet<clash> clashes { get; set; }
        public virtual DbSet<conductsurvey> conductsurveys { get; set; }
        public virtual DbSet<confirmVenue> confirmVenues { get; set; }
        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<Crsdtl> Crsdtls { get; set; }
        public virtual DbSet<crsdtl_enrl> crsdtl_enrl { get; set; }
        public virtual DbSet<CRSMTR> CRSMTRs { get; set; }
        public virtual DbSet<CrsmtrShort> CrsmtrShorts { get; set; }
        public virtual DbSet<duty> duties { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GroupMember> GroupMembers { get; set; }
        public virtual DbSet<InstDate> InstDates { get; set; }
        public virtual DbSet<InstDate2> InstDate2 { get; set; }
        public virtual DbSet<Population> Populations { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Question_Answer> Question_Answer { get; set; }
        public virtual DbSet<seat> seats { get; set; }
        public virtual DbSet<sectiontbl> sectiontbls { get; set; }
        public virtual DbSet<SEMMTR> SEMMTRs { get; set; }
        public virtual DbSet<short_attendance> short_attendance { get; set; }
        public virtual DbSet<ST_REMARKS> ST_REMARKS { get; set; }
        public virtual DbSet<STMTRold> STMTRolds { get; set; }
        public virtual DbSet<stuapp> stuapps { get; set; }
        public virtual DbSet<Student_Relationship> Student_Relationship { get; set; }
        public virtual DbSet<survey> surveys { get; set; }
        public virtual DbSet<surveyaudience> surveyaudiences { get; set; }
        public virtual DbSet<surveyquestion> surveyquestions { get; set; }
        public virtual DbSet<surveyresponse> surveyresponses { get; set; }
        public virtual DbSet<tbl_User_Roles> tbl_User_Roles { get; set; }
        public virtual DbSet<teacher> teachers { get; set; }
        public virtual DbSet<temp_venue> temp_venue { get; set; }
        public virtual DbSet<Temp1> Temp1 { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
        public virtual DbSet<THESIS_ENTRY> THESIS_ENTRY { get; set; }
        public virtual DbSet<venue> venues { get; set; }
        public virtual DbSet<ALLOCATE> ALLOCATEs { get; set; }
        public virtual DbSet<CrsdtlTemp> CrsdtlTemps { get; set; }
        public virtual DbSet<CrsEnrF> CrsEnrFs { get; set; }
        public virtual DbSet<CrsEnrp> CrsEnrps { get; set; }
        public virtual DbSet<CrsFail> CrsFails { get; set; }
        public virtual DbSet<CRSPRE> CRSPREs { get; set; }
        public virtual DbSet<DscplnEntry> DscplnEntries { get; set; }
        public virtual DbSet<EMPMTR> EMPMTRs { get; set; }
        public virtual DbSet<EMPMTR_E> EMPMTR_E { get; set; }
        public virtual DbSet<Eval> Evals { get; set; }
        public virtual DbSet<Log_In> Log_In { get; set; }
        public virtual DbSet<meritTemp> meritTemps { get; set; }
        public virtual DbSet<semReg> semRegs { get; set; }
        public virtual DbSet<sReg> sRegs { get; set; }
        public virtual DbSet<STMTR> STMTRs { get; set; }
        public virtual DbSet<STMTRtemp> STMTRtemps { get; set; }
        public virtual DbSet<temp> temps { get; set; }
        public virtual DbSet<TempCr> TempCrs { get; set; }
        public virtual DbSet<TempCrs2> TempCrs2 { get; set; }
        public virtual DbSet<TEMPCrsdtl> TEMPCrsdtls { get; set; }
        public virtual DbSet<tempFEE> tempFEEs { get; set; }
    }
}
