//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Population
    {
        public int id { get; set; }
        public string section { get; set; }
        public string semester { get; set; }
        public string discipline { get; set; }
        public string gender { get; set; }
        public Nullable<int> survey_id { get; set; }
    }
}
