//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seat
    {
        public string reg_no { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public string room { get; set; }
        public string row { get; set; }
        public string seat1 { get; set; }
        public string images { get; set; }
        public string section_no { get; set; }
        public string course_no { get; set; }
    }
}
