//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sectiontbl
    {
        public string emp_no { get; set; }
        public string reg_no { get; set; }
        public string course_no { get; set; }
        public string section { get; set; }
        public string discipline { get; set; }
        public string semC { get; set; }
        public string semester_no { get; set; }
        public string deleted { get; set; }
    }
}
