//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_REMARKS
    {
        public string REG_NO { get; set; }
        public string SEMESTER_NO { get; set; }
        public string REMARKS { get; set; }
        public string EMP_NO { get; set; }
    }
}
