//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Relationship
    {
        public string St_reg_no1 { get; set; }
        public string St_reg_no2 { get; set; }
        public string Relationship { get; set; }
        public string Discount { get; set; }
        public string St_first_name { get; set; }
        public string St_last_name { get; set; }
        public string Discipline { get; set; }
        public string Disc_allow { get; set; }
    }
}
