//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_venue
    {
        public string room { get; set; }
        public string total_seat { get; set; }
        public string no_of_rows { get; set; }
        public string row1 { get; set; }
        public string row2 { get; set; }
        public string row3 { get; set; }
        public string row4 { get; set; }
        public string row5 { get; set; }
        public string row6 { get; set; }
        public string row7 { get; set; }
        public Nullable<int> id { get; set; }
    }
}
