//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp1
    {
        public long Id { get; set; }
        public string Course_no { get; set; }
        public string Attempt_no { get; set; }
        public string Reg_no { get; set; }
        public string Emp_no { get; set; }
        public string Semester_no { get; set; }
        public string Section { get; set; }
        public string Discipline { get; set; }
        public string Semester { get; set; }
    }
}
