//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempCr
    {
        public string Course_no { get; set; }
        public string reg_no { get; set; }
        public string Credit_hrs { get; set; }
        public Nullable<decimal> Q_points { get; set; }
        public string Discipline { get; set; }
        public string Section { get; set; }
    }
}
